base/shared/annotation.js, lib/pdfanno.js, lib/pdffield.js
TM key is used on Form submissions. It's necessary while matching the field ID at backend
=> AcroForms :: 'TM' as an alternative field ID

lib/pdffont.js
I have updated the code to extend existing fix for issue #42 and added another detection - bolditalic fonts. So, when we don't have bold or italic set, and fonr identifies itself by "boldobl" in it's name, set bold and italic properties of the text.
It is possible that this doesn't cover all possible situations. This fix is made from my own situation where existing bold/italic detection has failed.
=> Additional bold italic detection

.gitignore, base/display/canvas.js
When render a data table in my project, some spacing between numbers will be merged and look weird, so I fix it to suit my own situation
An example here
=> Word spacing adjustment

lib/pdfanno.js
I was getting a `no such function jsFuncName` error on `processFieldAttribute`. This fix solved the issue, and it still processed the fields correctly.
=> Fixed bug on some pdfs with fields

readme.md
This field is documented in the code but was missing from the README.
=> Document Pages->Texts->R->TS in readme.md

base/shared/annotation.js
For a specific PDF I have, url is undefined and this line fails (indexOf of undefined), this resolves it.
https://github.com/modesty/pdf2json/issues/158
=> Do not fail if url is undefined

package.json
A security advisory was released for lodash version <= 4.17.12 https://snyk.io/vuln/SNYK-JS-LODASH-450202.
This patch updates to a version where the issue is fixed.
Ran tests locally and all passing after update.
=> Update lodash to 4.17.15

package.json
There are vulernabilities found in the version of lodash currently used. These issues are detailed here:
https://nodesecurity.io/advisories/577
They are fixed in async version >=2.6.1 (remove lodash)
This update upgrades the version of async to a more secure version.
npm tests passed successfully.
=> fix(deps): update async to v2.6.1 to remove vulnerabilities

package-lock.json, package.json
There are vulernabilities found in the version of lodash currently used.  These issues are detailed here:
https://nodesecurity.io/advisories/577   
They are fixed in lodash version >=4.17.5
This update upgrades the version of lodash to a more secure version.
npm tests passed successfully.
=> Updated lodash to remove vulnerabilities

lib/pdffield.js
Added a check for dropdown/select options to handle options with only a name string, instead of an array with name and value pairs.
Fixes #214
=> Handle dropdown options with only a name

readme.md
Fixing "TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined". Issues: #169 and #191
=> Fix "Callback must be a function" error

base/core/parser.js
Fixes #217, fixes #210 
These changes were adapted from a recent version of PDF.js which no longer throws an error when the name is too long and instead logs a warning, so the PDF should be able to be parsed.
=> Warn instead of error when name token longer than spec

base/display/canvas.js
Fixes #182 
These changes were adapted from a recent version of PDF.js, and they've been used in production code for a few months now so they should be safe. They will allow successful parsing of the PDF attached in the linked issue.
=> Fixed infinite loop with paintFormXObjectEnd

base/display/canvas.js
On some documents `CanvasGraphics.showText` can be run prior to `CanvasGraphics.setFont`, thus causing a `TypeError`. This quick hack allows such documents to work.
Fixes modesty/pdf2json#244.
=> Prevent `Cannot read property 'vertical' of undefined`

base/shared/annotation.js, lib/pdffield.js
The value of checkboxes was read within the code, but never given to the user in the final pdf data. This change gives a 'checked' value within boxes.
=> Give the checked status of checkboxes, for parsing checkboxes in forms

.npmignore
Hi,
I don't think you should be publishing your jetbrains settings.
Also, may I ask why do you bundle xmldom within the module? Why not keep it as a normal dependency?
=> Exclude IDE settings from publish

base/display/canvas.js
Fixes #266 
Tracking whether or not we are in a NO_OPS_RANGE on the CanvasGraphics instance instead of only within the current iteration of executeOperatorList() allows the PDF in the issue to parse successfully. Here's the output (with some temporary extra logging) to show the fixed behaviour of "NO_OP" Begin and "NO_OP End" when spanning multiple op lists:
```
Info: start to parse page:18
Info: Skipped: tiny fill: 0 x 0
Info: END OP LIST: - 0
Info: NO_OP Begin: CanvasGraphics_beginAnnotations - 5
Info: END OP LIST: - 100
Info: END OP LIST: - 200
Info: END OP LIST: - 300
Info: END OP LIST: - 400
Info: END OP LIST: - 500
Info: END OP LIST: - 600
Info: END OP LIST: - 700
Info: END OP LIST: - 800
Info: END OP LIST: - 900
Info: NO_OP End: CanvasGraphics_endAnnotations - 968
Info: END OP …
```
=> Fixed NO_OPS_RANGE spanning multiple executeOperatorList

base/shared/annotation.js, lib/pdfanno.js, lib/pdffield.js, lib/pdfunit.js, readme.md
Closes #78 
Added support for signature form fields. They are added into the 'Fields' array, and have a 'Name' of 'signature'. If the field has been signed, it will contain any available details of the signer, such as name, time, etc. I tentatively updated the readme with an example and more information on the signer details. Just the released version number needs to be replaced when ready (v2.X.X).
The time of the signature is converted from PDF's internal datetime format into ISO 8601 for ease of use, since the PDF spec allows for a lot of variation.
Here's a basic PDF that can be used to test this (in addition to the one from the linked issue): [signature_widget_signed.pdf](https://github.com/modesty/pdf2json/files/8258012/signature_widget_signed.pdf). I'm not sure where the best place …
=> Add signature field support

base/shared/colorspace.js
pdf2json doesn't work with pdf in LabCS colorspace, it throws the following error:
```
Warning: Unhandled rejection: TypeError: this.colorSpace.createRgbBuffer is not a function
TypeError: this.colorSpace.createRgbBuffer is not a function
at PDFImage_fillRgbaBuffer [as fillRgbaBuffer] (eval at <anonymous> (/Users/davidecampagnola/Tutored/pdf2json/lib/pdf.js:62:1), <anonymous>:20964:36)
at PDFImage_getImageData [as getImageData] (eval at <anonymous> (/Users/davidecampagnola/Tutored/pdf2json/lib/pdf.js:62:1), <anonymous>:21014:12)
at eval (eval at <anonymous> (/Users/davidecampagnola/Tutored/pdf2json/lib/pdf.js:62:1), <anonymous>:7135:34)
at Object.eval [as onResolve] (eval at <anonymous> (/Users/davidecampagnola/Tutored/pdf2json/lib/pdf.js:62:1), <anonymous>:20667:7)
at Object.runHandlers …
```
=> fix(LabCS-colorspace): createRgbBuffer missing in LabCS colorspace

base/core/evaluator.js
don't add resources that are self references or references to nodes that have been seen before to avoid infinite loops
=> fix infinite loop in hasBlendModes

pdfparser.d.ts
Update PDFParser constructor with typed parameters. See my [comment](https://github.com/modesty/pdf2json/issues/273#issuecomment-1662587255) on an issue explaining why this is needed.
=> Update TypeScript Definitions for PDFParser Constructor

pdfparser.d.ts, pdfparser.js
This PR introduces a new parameter for the parseBuffer method so that one can toggle the verbosity used within this function.
After this PR, I would like to open a PR that adds documentation to pdfparser.js so that open source contribution is more welcome going forward in the future (please reference [docs/document-pdfparser-class](https://github.com/nql5161/pdf2json/tree/docs/document-pdfparser-class))
Thank you!
=> Enhance parsebuffer logging

pdfparser.d.ts
Fixes compilation error:
```
> tsc
node_modules/pdf2json/pdfparser.d.ts:132:16 - error TS2552: Cannot find name 'Pdfparser'. Did you mean 'PDFParser'?
132 export default Pdfparser
~~~~~~~~~
node_modules/pdf2json/pdfparser.d.ts:3:15
3 declare class PDFParser extends EventEmitter{
~~~~~~~~~
'PDFParser' is declared here.
Found 1 error in node_modules/pdf2json/pdfparser.d.ts:132
```
=> Fix name for the export of PDF parser

lib/pdffont.js
`WHYXTS+NimbusRomNo9L-Medi` should be in the bolded category
https://github.com/modesty/pdf2json/pull/108#issuecomment-2097646106
=> ✨  improve detection of bold font

rollup/bundle-pdfjs-base.js
Output typescript definition for pdfparser.cjs.
If the following compiler options are set, importing pdf2json causes an error if `pdfparser.d.cts` is not present:
- `module: "NodeNext"` and `moduleResolution: "NodeNext"`
- `noImplicitAny: true`
The resulting error is as follows:
```
error TS7016: Could not find a declaration file for module 'example-package'. '/home/naoki/WorkDir/js/modtest/node_modules/pdf2json/dist/pdfparser.cjs' implicitly has an 'any' type.
Try `npm i --save-dev @types/pdf2json` if it exists or add a new declaration (.d.ts) file containing `declare module 'pdf2json';`
import PDFParser from 'pdf2json';
~~~~~~~~~~
```
=> feat: add commonjs type definition file generation

package.json
When resolving modules with TypeScript via the package.json "exports" spec, the type declaration for this package is currently not resolved properly.
This PR fixes that by including the "types" field under "exports" > ".", and resolving to the existing type declaration file.
```sh
mkdir demo
cd demo
npm i pdf2json@3.1.2
npm i typescript@5.6.3
echo '{"include":["main.ts"],"compilerOptions":{"target":"ES2015","moduleResolution":"Bundler"}}' >> tsconfig.json
echo 'import PDFParser from "pdf2json"' >> main.ts
npx tsc --skipLibCheck --noImplicitAny
```
TypeScript will report,
```
main.ts:1:23 - error TS7016: Could not find a declaration file for module 'pdf2json'. '.../demo/node_modules/pdf2json/dist/pdfparser.js' implicitly has an 'any' type.
There are types at …
```
=> add 'types' to package.json 'exports' root

package.json
This makes sure that `npm` is only enforced for developers in this repo but once published to npm, consumers can use whatever package manager they wish.
See the docs here:
- https://github.com/openjs-foundation/package-metadata-interoperability-collab-space/blob/main/devengines-field-proposal.md
- https://docs.npmjs.com/cli/v11/configuring-npm/package-json#devengines
=> fix: move package manager version from `engines` to `devEngines`

lib/ptixmlinject.js, lib/simpleXmlParser.js, package.json, readme.md, rollup.config.js, rollup/bundle-pdfjs-base.js
=> maint: remove dependency on @xmldom/xmldom

base/display/canvas.js, package.json, test/_test_.cjs
=> fix: #408: fix text block coordinates

base/core/evaluator.js, lib/pdf.js
font metrics based solution to calcualte and detect spaces, preserve the spaces in both .content.txt and json output
=> fix: #355, #361, #319: calculate text block gap and spacewidth 
